@startuml
!theme blueprint

interface HTTP
component "Spring Boot" <<OpenTelemetry>> as springBoot
component "Spring Boot Client" <<MicroMeter>> as springBootClient
component "OpenTelemetry Collector" as otelCollector
database "Prometheus Database" as prometheus <<Time Series>>
component "Grafana Dashboard" as grafana
database "Tempo" as tempo
database "Loki" as loki

database "H2 Database" as books <<RDBMS>>

HTTP .right. springBootClient
springBoot -down-> books : jdbc
springBootClient <-right-> springBoot : REST

springBoot -down-> otelCollector : OTLP
springBootClient -down-> otelCollector : OTLP

otelCollector -down-> prometheus : <<pull prometheus>> /metrics
otelCollector -down-> tempo : OTLP
otelCollector -down-> loki : otlphttp
grafana <-up-> prometheus : HTTP
grafana <-up-> loki : HTTP
grafana <-up-> tempo : HTTP
@enduml
