language: java
jdk:
  - oraclejdk8
install:
  - true
script: 
  - gradle jbake
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && chmod +x deploy.sh && bash deploy.sh
